// Auto-generated by CMAKE script.
#ifndef SORTING_GROUP_PROJECT_SORT_H
#define SORTING_GROUP_PROJECT_SORT_H

#include "sort/binary_insertion_sort.cpp"
#include "sort/bubble_sort.cpp"
#include "sort/counting_sort.cpp"
#include "sort/flash_sort.cpp"
#include "sort/heap_sort.cpp"
#include "sort/insertion_sort.cpp"
#include "sort/merge_sort.cpp"
#include "sort/quick_sort.cpp"
#include "sort/radix_sort.cpp"
#include "sort/selection_sort.cpp"
#include "sort/shaker_sort.cpp"
#include "sort/shell_sort.cpp"

#endif //SORTING_GROUP_PROJECT_SORT_H
